# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/workspace/twitch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/workspace/twitch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/twitch/CMakeFiles /home/ubuntu/workspace/twitch/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/twitch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bot.out

# Build rule for target.
bot.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bot.out
.PHONY : bot.out

# fast build rule for target.
bot.out/fast:
	$(MAKE) -f CMakeFiles/bot.out.dir/build.make CMakeFiles/bot.out.dir/build
.PHONY : bot.out/fast

bot.o: bot.cpp.o
.PHONY : bot.o

# target to build an object file
bot.cpp.o:
	$(MAKE) -f CMakeFiles/bot.out.dir/build.make CMakeFiles/bot.out.dir/bot.cpp.o
.PHONY : bot.cpp.o

bot.i: bot.cpp.i
.PHONY : bot.i

# target to preprocess a source file
bot.cpp.i:
	$(MAKE) -f CMakeFiles/bot.out.dir/build.make CMakeFiles/bot.out.dir/bot.cpp.i
.PHONY : bot.cpp.i

bot.s: bot.cpp.s
.PHONY : bot.s

# target to generate assembly for a file
bot.cpp.s:
	$(MAKE) -f CMakeFiles/bot.out.dir/build.make CMakeFiles/bot.out.dir/bot.cpp.s
.PHONY : bot.cpp.s

irc.o: irc.cpp.o
.PHONY : irc.o

# target to build an object file
irc.cpp.o:
	$(MAKE) -f CMakeFiles/bot.out.dir/build.make CMakeFiles/bot.out.dir/irc.cpp.o
.PHONY : irc.cpp.o

irc.i: irc.cpp.i
.PHONY : irc.i

# target to preprocess a source file
irc.cpp.i:
	$(MAKE) -f CMakeFiles/bot.out.dir/build.make CMakeFiles/bot.out.dir/irc.cpp.i
.PHONY : irc.cpp.i

irc.s: irc.cpp.s
.PHONY : irc.s

# target to generate assembly for a file
irc.cpp.s:
	$(MAKE) -f CMakeFiles/bot.out.dir/build.make CMakeFiles/bot.out.dir/irc.cpp.s
.PHONY : irc.cpp.s

twitch.o: twitch.cpp.o
.PHONY : twitch.o

# target to build an object file
twitch.cpp.o:
	$(MAKE) -f CMakeFiles/bot.out.dir/build.make CMakeFiles/bot.out.dir/twitch.cpp.o
.PHONY : twitch.cpp.o

twitch.i: twitch.cpp.i
.PHONY : twitch.i

# target to preprocess a source file
twitch.cpp.i:
	$(MAKE) -f CMakeFiles/bot.out.dir/build.make CMakeFiles/bot.out.dir/twitch.cpp.i
.PHONY : twitch.cpp.i

twitch.s: twitch.cpp.s
.PHONY : twitch.s

# target to generate assembly for a file
twitch.cpp.s:
	$(MAKE) -f CMakeFiles/bot.out.dir/build.make CMakeFiles/bot.out.dir/twitch.cpp.s
.PHONY : twitch.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bot.out"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bot.o"
	@echo "... bot.i"
	@echo "... bot.s"
	@echo "... irc.o"
	@echo "... irc.i"
	@echo "... irc.s"
	@echo "... twitch.o"
	@echo "... twitch.i"
	@echo "... twitch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

